fix(channel-webview-electron): add electron to dev dependencies for ../../node_modules/electron/electron.d.ts(6594,21): error TS2694: Namespace 'NodeJS' has no exported member 'Require'